# Generated by Django 4.1.7 on 2026-09-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('activity_type', models.CharField(max_length=40)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('points', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateField()),
            ],
            options={
                'db_table': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('team', models.CharField(max_length=80)),
                ('points', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'leaderboard',
                'ordering': ['rank', 'user_email'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('team', models.CharField(blank=True, max_length=80)),
                ('fitness_level', models.CharField(default='beginner', max_length=40)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=40)),
                ('difficulty', models.CharField(max_length=40)),
                ('duration_minutes', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'workouts',
            },
        ),
    ]
